{% set name = "treefmt" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/numtide/treefmt/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4cd20c3cf763bbf4054b9241e6d59de4d59bb4705a758a666d1661685294f2e7

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - treefmt --help

about:
  home: https://github.com/numtide/treefmt
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: one CLI to format your repo
  dev_url: https://github.com/numtide/treefmt

extra:
  recipe-maintainers:
    - danielnachun
