schema_version: 1

context:
  version: "2.5.0"

package:
  name: treefmt
  version: ${{ version|replace("-", "_") }}

source:
  url: https://github.com/numtide/treefmt/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0d30d2d2a0faf642f8c13c00b7e71a58e4e72f0c403a0e478caea4ab596ad8f8

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - treefmt --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: one CLI to format your repo
  homepage: https://github.com/numtide/treefmt
  repository: https://github.com/numtide/treefmt

extra:
  recipe-maintainers:
    - danielnachun
