schema_version: 1

context:
  version: "2.4.1"

package:
  name: treefmt
  version: ${{ version|replace("-", "_") }}

source:
  url: https://github.com/numtide/treefmt/archive/refs/tags/v${{ version }}.tar.gz
  sha256: b798ea210346474ce7f90dc062e849615abdbfeac1219d88d16bb1da7ce5566b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - treefmt --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: one CLI to format your repo
  homepage: https://github.com/numtide/treefmt
  repository: https://github.com/numtide/treefmt

extra:
  recipe-maintainers:
    - danielnachun
