schema_version: 1

context:
  version: "2.6.0"

package:
  name: treefmt
  version: ${{ version|replace("-", "_") }}

source:
  url: https://github.com/numtide/treefmt/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 90993f858b376c0a0ca49920b9679dc774107a96fad8ffc3808809c6a82f4ece

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - treefmt --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: one CLI to format your repo
  homepage: https://github.com/numtide/treefmt
  repository: https://github.com/numtide/treefmt

extra:
  recipe-maintainers:
    - danielnachun
